# Official docker compose image.
image:
  name: docker/compose:latest

services:
  - docker:dind

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


before_script:
  - docker version
  - docker-compose version

stages:
  - publish
  - deploy

publish:
  stage: publish
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - echo "IMAGE_APP_TAG=$TAG_LATEST" >> .env
    - docker-compose build
    - docker-compose push

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" down --remove-orphans
    - docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" pull
    - docker-compose -H "ssh://$SERVER_USER@$SERVER_IP" up -d
  environment:
    name: production
    url: http://3.214.98.239
  only:
    - main
